# Prediction parameters:
prediction_countries:
  - 'Dem_Rep_Korea'
  - 'Russian_Federation'
  - 'Finland'
  - 'Norway'
  - 'Sweden'
  - 'Lithuania'
  - 'Latvia'
  - 'Estonia'
  - 'Poland'
  - 'Czech_Republic'
  - 'Hungary'
  - 'Slovakia'
  - 'Belarus'
  - 'Moldova'
  - 'Romania'
  - 'Bulgaria'
  - 'Albania'
  - 'Montenegro'
  - 'Macedonia_Former_Yugoslav_Republic_of'
  - 'Kosovo'
  - 'Serbia'
  - 'Croatia'
  - 'Bosnia_and_Herzegovina'
  - 'Slovenia'
  - 'Greece'
  - 'Turkey'
  - 'Georgia'
  - 'Azerbaijan'
  - 'Armenia'
  - 'Kazakhstan'
  - 'Kyrgyzstan'
  - 'Tajikistan'
  - 'Mongolia'

selected_feature_columns_path: "configs/selected_columns_30d.txt"
prepared_prediction_features_path: "data/outputs/prepared_prediction_features.parquet"
model_path: "models/catboost_fire_model_30d.cbm"
nn_model_path: "models/lstm_ml_fire-lstm_mlp-epoch=00-val_ap=0.7810.ckpt"


# Feature generation configuration
# Should be the same for train, test and prediction

# Target generation from MODIS settings:
modis_data_path: 'data/modis/'
modis_countries:
  - 'Dem_Rep_Korea'
  - 'Russian_Federation'
  - 'Finland'
  - 'Norway'
  - 'Sweden'
  - 'Lithuania'
  - 'Latvia'
  - 'Estonia'
  - 'Poland'
  - 'Czech_Republic'
  - 'Hungary'
  - 'Slovakia'
  - 'Belarus'
  - 'Moldova'
  - 'Romania'
  - 'Bulgaria'
  - 'Albania'
  - 'Montenegro'
  - 'Macedonia_Former_Yugoslav_Republic_of'
  - 'Kosovo'
  - 'Serbia'
  - 'Croatia'
  - 'Bosnia_and_Herzegovina'
  - 'Slovenia'
  - 'Greece'
  - 'Turkey'
  - 'Georgia'
  - 'Azerbaijan'
  - 'Armenia'
  - 'Kazakhstan'
  - 'Kyrgyzstan'
  - 'Tajikistan'
  - 'Mongolia'
  - 'Ukraine'

target_samples_per_area_per_year: 18
target_start_date: "2000-01-01"  
target_end_date: "2025-06-09"
coordinate_bounds: [35, 1, 75, 179] #[40, 20, 70, 170] #[34, 30, 60, 130] # [40, 70, 60, 110] [34, 70, 60, 130]

# Data split parameters for training
train_end: "2021-01-01"
val_end: "2023-01-31"

generate_climate_params:
  n_days: 128

climate_data_params:
  climate_data_dir: "data/climate_data_files/ECMWF"
  climate_variables: ["t2m", "d2m", "tp", "stl1"]
  n_days: 128


skip_climate: False

climate_data_params_prediction:
  climate_data_dir: "data/climate_data_files/ECMWF_prediction"
  climate_variables: ["t2m", "d2m", "tp", "stl1"]
  n_days: 128
  

# Elevation data parameters
elevation_data_params:
  elevation_file: "data/land_features/GMTED2010_15n015_00625deg.nc"
  window_size: [0.1, 0.20]

# Road data parameters. Not used
road_data_params:
  feature_map_path: "data/land_features/roads_features.npz"

# Fire data parameters. Not used
fire_data_params:
  density_radii_km: 50

# Land data parameters
land_data_params:
  land_data_files: ["data/land_features/forest_data.nc",
                    "data/land_features/IMERG_land_sea_mask.nc",
                    "data/land_features/kontur_population_20231101_r6.gpkg",
                    "data/land_features/topography.nc",
                    data/land_features/type_of_high_vegetation_0_daily-mean.nc,
                    data/land_features/type_of_low_vegetation_0_daily-mean.nc,
                    data/land_features/soil_type_stream-oper_daily-mean.nc]
                    
  fire_index_npz_path: "data/land_features/fire_index_features.npz"
  wwf_shp_path: "data/wwf_terr_ecos"

country_shapes_path: "data/countries"

# Training data generation paths
train_features_parquet_path: "data/saved_features/train_features_nn_30d_06cb.parquet"
output_plots_dir: "outputs/plots"
output_train_data_dir: "data/saved_features/nn_train_data"
target_cache_path: "data/saved_features/target_data.parquet"

cat_features: ["ecoregion_name", "ecoregion_realm", "slt", "tvl", "tvh", "slt_soil_type_stream_oper_daily_mean"]
numerical_cat_features: ["slt", "tvl", "tvh", "slt_soil_type_stream_oper_daily_mean"]

epochs: 10
num_workers: 6

# Neural network architecture options.
# Available architectures: lstm_mlp (default), lstm_attention.
batch_size: 2048
epochs: 10
num_workers: 6
nn_model:
  architecture: lstm_mlp
  params:
    lstm_units: 196
    dropout_lstm: 0.1
    merge_units: 256
    dropout_merged: 0.2
  lightning:
    learning_rate: 0.003
    decay_rate: 0.5
    l2: 0.0
    clip_gradient_norm: 5.0
  scheduler_config:
    type: cosine  # Options: lambda, step, cosine, reduce_on_plateau
    interval: epoch  # Options: step, epoch
    frequency: 1
    params:
      T_max: 15  # Number of iterations for cosine annealing (will use decay_steps if not specified)
      eta_min: 0.0  # Minimum learning rateq    
  trainer: {}

class_weights:
  0: 1.0
  1: 2.0
  
  # Example for attention-based model:
  # architecture: lstm_attention
  # params:
  #   bidirectional: true
  #   lstm_units: 256
